#!/usr/bin/env python3
"""Generate LaTeX tables from data/experiments/ for PAPER/latex/tables/."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_EXP = PROJECT_ROOT / "data" / "experiments"
DEFAULT_OUT = PROJECT_ROOT.parent / "PAPER" / "latex" / "tables"

TIER_LABELS = {0: "Tier 0", 1: "Tier 1", 2: "Tier 2"}
MODEL_LABELS = {
    "vgg16": "VGG16",
    "resnet50": "ResNet50",
    "efficientnet_b0": "EfficientNet-B0",
    "vit_b_16": "ViT-B/16",
    "cnn_glcm": "CNN+GLCM",
    "lbpnet": "LBPNet",
    "waveletcnn": "WaveletCNN",
    "cnn_hog": "CNN+HOG",
    "multibranch_fusion": "MultiBranchFusion",
    "attention_fusion": "AttentionFusion",
}


def esc(s: str) -> str:
    return (
        str(s)
        .replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
    )


def fmt(x: float | str | None, digits: int = 4) -> str:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "---"
    if isinstance(x, str):
        if not x or x.upper() == "TODO":
            return "TODO"
        try:
            return f"{float(x):.{digits}f}"
        except ValueError:
            return x
    return f"{float(x):.{digits}f}"


def write_table(path: Path, caption: str, label: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = f"""% Auto-generated by tables_to_latex.py — do not edit by hand
\\begin{{table}}[!t]
\\centering
\\caption{{{esc(caption)}}}
\\label{{{label}}}
{body}
\\end{{table}}
"""
    path.write_text(content, encoding="utf-8")
    print(f"[tables] Wrote {path.name}")


def table_phase1(out_dir: Path) -> None:
    src = DATA_EXP / "phase1_param_search.json"
    if not src.exists():
        print(f"[tables] Skip phase1: missing {src}")
        return
    data = json.loads(src.read_text(encoding="utf-8"))
    rows = []
    for ext, info in data.get("extractors", {}).items():
        best = info.get("best", {})
        rows.append(
            (
                ext.upper(),
                best.get("label", "---"),
                best.get("n_features", "---"),
                fmt(best.get("score")),
            )
        )
    lines = [
        "\\begin{tabular}{@{}llcc@{}}",
        "\\toprule",
        "Extractor & Best config & Dim & Score \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(f"{esc(r[0])} & {esc(r[1])} & {r[2]} & {r[3]} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "phase1_params.tex",
        "Phase 1 optimal feature extractor parameters.",
        "tab:phase1",
        "\n".join(lines),
    )


def table_phase2_models(out_dir: Path) -> None:
    """Phase 2 classifier search spaces (from notebook MODEL_GRIDS)."""
    rows = [
        ("SVM", "4 kernels, C, $\\gamma$, degree, coef$_0$", "903", "4,515"),
        ("KNN", "n\\_neighbors, metric, weights, p", "384", "1,920"),
        ("Random Forest", "n\\_estimators, max\\_depth, max\\_features, criterion", "14,112", "70,560"),
        ("XGBoost", "n\\_estimators, max\\_depth, lr, subsample, colsample", "6,480", "32,400"),
        ("LightGBM", "n\\_estimators, max\\_depth, lr, num\\_leaves, subsample", "13,824", "69,120"),
        ("Logistic Reg.", "C, penalty (L1/L2/elastic-net), class\\_weight", "108", "540"),
        ("MLP", "hidden\\_layers, activation, $\\alpha$, lr, batch", "432", "2,160"),
        ("ExtraTrees", "n\\_estimators, max\\_features, min\\_samples", "162", "810"),
    ]
    lines = [
        "\\begin{tabular}{@{}llcc@{}}",
        "\\toprule",
        "Model & Key hyperparameters & Candidates & $\\times$ 5-fold CV \\\\",
        "\\midrule",
    ]
    for model, params, cand, cv in rows:
        lines.append(f"{esc(model)} & {params} & {cand} & {cv} \\\\")
    lines += [
        "\\midrule",
        "\\textbf{Total} & & \\textbf{36,405} & \\textbf{182,025} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    write_table(
        out_dir / "phase2_models.tex",
        "Phase 2 classifier hyperparameter search spaces (per model, before $\\times$ eight feature sets).",
        "tab:phase2_models",
        "\n".join(lines),
    )


def table_phase2_top10(out_dir: Path) -> None:
    src = DATA_EXP / "phase2_all_modes_metrics.csv"
    if not src.exists():
        print(f"[tables] Skip phase2: missing {src}")
        return
    df = pd.read_csv(src)
    split = df[df["eval_mode"] == "split"].copy()
    split = split.sort_values("f1_macro", ascending=False).head(10)
    lines = [
        "\\begin{tabular}{@{}lllcc@{}}",
        "\\toprule",
        "Model & Feature set & Eval & Acc & F1 \\\\",
        "\\midrule",
    ]
    for _, row in split.iterrows():
        lines.append(
            f"{esc(row['model'])} & {esc(row['feature_set'])} & split "
            f"& {fmt(row['acc'])} & {fmt(row['f1_macro'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "phase2_top10.tex",
        "Top-10 Phase 2 classical ML configurations (held-out split).",
        "tab:phase2_top10",
        "\n".join(lines),
    )


def table_dl_all(out_dir: Path) -> None:
    src = DATA_EXP / "phase3_all_metrics.csv"
    if not src.exists():
        src = PROJECT_ROOT.parent / "results" / "phase3_all_metrics.csv"
    if not src.exists():
        print("[tables] Skip dl_all: no phase3 metrics")
        return
    df = pd.read_csv(src)
    split = df[df["eval_mode"] == "split"].copy()
    lines = [
        "\\begin{tabular}{@{}llccc@{}}",
        "\\toprule",
        "Tier & Model & Acc & F1-macro & Time (s) \\\\",
        "\\midrule",
    ]
    for _, row in split.sort_values(["tier", "model"]).iterrows():
        tier = int(row["tier"])
        model = MODEL_LABELS.get(row["model"], row["model"])
        lines.append(
            f"{TIER_LABELS.get(tier, tier)} & {esc(model)} "
            f"& {fmt(row['acc'])} & {fmt(row['f1_macro'])} "
            f"& {fmt(row.get('fit_time_s'), 1)} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "dl_all_models.tex",
        "Phase 3 deep learning models on the held-out split.",
        "tab:dl_all",
        "\n".join(lines),
    )


def table_ablation(out_dir: Path) -> None:
    src = DATA_EXP / "phase3_all_metrics.csv"
    if not src.exists():
        src = PROJECT_ROOT.parent / "results" / "phase3_all_metrics.csv"
    if not src.exists():
        return
    df = pd.read_csv(src)
    split = df[df["eval_mode"] == "split"].set_index("model")

    def f1(model: str) -> float | None:
        if model not in split.index:
            return None
        return float(split.loc[model, "f1_macro"])

    hybrid_scores = [
        f1("cnn_glcm"),
        f1("lbpnet"),
        f1("waveletcnn"),
        f1("cnn_hog"),
    ]
    hybrid_scores = [s for s in hybrid_scores if s is not None]
    best_hybrid_f1 = max(hybrid_scores) if hybrid_scores else 0.0

    rows = [
        ("CNN only (VGG16)", "---", "---", "---", "---", f1("vgg16"), "baseline"),
        ("CNN+GLCM", "\\checkmark", "---", "---", "---", f1("cnn_glcm"), "hybrid"),
        ("CNN+LBP", "---", "\\checkmark", "---", "---", f1("lbpnet"), "hybrid"),
        ("CNN+DWT", "---", "---", "\\checkmark", "---", f1("waveletcnn"), "hybrid"),
        ("CNN+HOG", "---", "---", "---", "\\checkmark", f1("cnn_hog"), "hybrid"),
        ("All branches", "\\checkmark", "\\checkmark", "\\checkmark", "\\checkmark", f1("multibranch_fusion"), "hybrid"),
    ]

    lines = [
        "\\begin{tabular}{@{}lcccccc@{}}",
        "\\toprule",
        "Model & GLCM & LBP & DWT & HOG & F1 & $\\Delta$F1 \\\\",
        "\\midrule",
    ]
    for label, glcm, lbp, dwt, hog, score, kind in rows:
        if score is None:
            delta = "---"
            score_s = "\\textbf{TODO}"
        elif kind == "baseline":
            delta = "---"
            score_s = fmt(score)
        else:
            delta = fmt(score - best_hybrid_f1)
            score_s = (
                f"\\textbf{{{fmt(score)}}}"
                if score == best_hybrid_f1
                else fmt(score)
            )
        lines.append(
            f"{esc(label)} & {glcm} & {lbp} & {dwt} & {hog} & {score_s} & {delta} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "ablation_features.tex",
        "Feature-branch ablation (held-out split). CNN-only baseline uses Tier-0 VGG16 until dedicated run completes.",
        "tab:ablation",
        "\n".join(lines),
    )


def table_training_config(out_dir: Path) -> None:
    rows = [
        ("Image size", "$128\\times128$"),
        ("Split", "70/10/20 stratified"),
        ("Batch size", "32"),
        ("Optimizer", "Adam"),
        ("Learning rate", "$10^{-4}$"),
        ("Early stopping", "patience 10 (val loss)"),
        ("CV", "5-fold"),
        ("AMP", "enabled (CUDA)"),
    ]
    lines = [
        "\\begin{tabular}{@{}ll@{}}",
        "\\toprule",
        "Setting & Value \\\\",
        "\\midrule",
    ]
    for k, v in rows:
        lines.append(f"{esc(k)} & {v} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "training_config.tex",
        "Shared Phase 3 training configuration.",
        "tab:training",
        "\n".join(lines),
    )


def table_vlm_config(out_dir: Path) -> None:
    rows = [
        ("Base model", "Qwen2-VL-2B"),
        ("Fine-tuning", "LoRA ($r=8$, $\\alpha=16$)"),
        ("Quantization", "4-bit NF4"),
        ("Teacher forcing", "enabled"),
    ]
    lines = [
        "\\begin{tabular}{@{}ll@{}}",
        "\\toprule",
        "Setting & Value \\\\",
        "\\midrule",
    ]
    for k, v in rows:
        lines.append(f"{esc(k)} & {v} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "vlm_config.tex",
        "Phase 4 VLM configuration.",
        "tab:vlm_config",
        "\n".join(lines),
    )


def table_stats_top5(out_dir: Path) -> None:
    src = DATA_EXP / "stats_top5.csv"
    if not src.exists():
        p2 = DATA_EXP / "phase2_all_modes_metrics.csv"
        rows = []
        if p2.exists():
            df2 = pd.read_csv(p2)
            split = df2[df2["eval_mode"] == "split"].copy()
            candidates = [
                ("KNN", "Full(opt)", "KNN Full(opt)"),
                ("SVM", "Full(opt)", "SVM Full(opt)"),
                ("KNN", "D — HOG", "KNN HOG"),
                ("SVM", "D — HOG", "SVM HOG"),
                ("RF", "Full(opt)", "RF Full(opt)"),
            ]
            for model, fs, label in candidates:
                sub = split[(split["model"] == model) & (split["feature_set"] == fs)]
                if not sub.empty:
                    rows.append(
                        {
                            "model": label,
                            "f1_macro": sub.iloc[0]["f1_macro"],
                            "ci_low": "",
                            "ci_high": "",
                            "kappa": "",
                            "mcnemar_p": "",
                            "friedman_rank": "",
                        }
                    )
        df_out = pd.DataFrame(rows)
    else:
        df_out = pd.read_csv(src)

    lines = [
        "\\begin{tabular}{@{}lcccccc@{}}",
        "\\toprule",
        "Model & F1 & CI low & CI high & $\\kappa$ & McNemar $p$ & Rank \\\\",
        "\\midrule",
    ]
    for _, row in df_out.iterrows():
        lines.append(
            f"{esc(row.get('model', ''))} "
            f"& {fmt(row.get('f1_macro') if row.get('f1_macro') != '' else None)} "
            f"& {row.get('ci_low', '---') or '---'} "
            f"& {row.get('ci_high', '---') or '---'} "
            f"& {row.get('kappa', '---') or '---'} "
            f"& {row.get('mcnemar_p', '---') or '---'} "
            f"& {row.get('friedman_rank', '---') or '---'} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table(
        out_dir / "stats_top5.tex",
        "Unified statistical validation for top Phase~2 models (populate stats\\_top5.csv after bootstrap/McNemar/Friedman runs).",
        "tab:stats",
        "\n".join(lines),
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Output directory for .tex tables",
    )
    args = parser.parse_args()
    table_phase1(args.out)
    table_phase2_models(args.out)
    table_phase2_top10(args.out)
    table_stats_top5(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
